/* Generated By:JavaCC: Do not edit this line. BnfParserConstants.java */
package net.hydromatic.clapham.parser.bnf;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BnfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 1;
  /** RegularExpression Id. */
  int LETTER = 2;
  /** RegularExpression Id. */
  int DIGIT = 3;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int HOOK = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int ASTERISK = 8;
  /** RegularExpression Id. */
  int COLCOLEQ = 9;
  /** RegularExpression Id. */
  int BAR = 10;
  /** RegularExpression Id. */
  int QUOT = 11;
  /** RegularExpression Id. */
  int BRACKETED_IDENTIFIER = 12;
  /** RegularExpression Id. */
  int LITERAL = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 21;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 22;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"?\"",
    "\"+\"",
    "\"*\"",
    "\"::=\"",
    "\"|\"",
    "\"\\\"\"",
    "<BRACKETED_IDENTIFIER>",
    "<LITERAL>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 23>",
  };

}
